defaults:
  - _self_

share_embedding: false
source_types: 2
attention_fusion_type: sw  # or linear
use_persona: true
use_cs: true  # cs: common sense
use_ef: true  # ef: empathy factors
predict_with_persona: true
pred_comae_coef: 1.0
decode_lm_coef: 1.0
encoder_decoder_is_same: false